image: smillerc/gfortran-dev:latest

# Set the thread count for OpenMP runs
variables:
  OMP_NUM_THREADS: 2
  HDF5_DISABLE_VERSION_CHECK: 2

before_script:
  - /bin/bash
  - eval `spack load --sh hdf5`

stages:
  - build
  - test

debug:
  stage: build
  script:
    - mkdir -p debug
    - cd debug
    - cmake .. -DCMAKE_BUILD_TYPE="Debug" -DENABLE_TESTING=YES -DUSE_OPENMP=YES
    - make -j
    - ctest

release:
  stage: build
  script:
    - mkdir -p release
    - cd release
    - pwd
    - cmake .. -DCMAKE_BUILD_TYPE="Release" -DENABLE_TESTING=YES -DUSE_OPENMP=YES
    - make -j
    - ctest

sod_1d:
  stage: test
  script:
    - cd tests/integrated/sod_1d/
    - cmake ../../.. -DCMAKE_BUILD_TYPE="Release" -DENABLE_TESTING=YES -DUSE_OPENMP=YES
    - make -j
    - python3 generate_ic.py
    - ./bin/cato.x input.ini
    - mv results/* .
    - python3 view_results.py
  artifacts:
    paths:
      - /builds/smil/cato/tests/integrated/sod_1d/sod_1d_results.png

kelvin_helmholtz_2d:
  stage: test
  script:
    - cd tests/integrated/kelvin_helmholtz/
    - cmake ../../.. -DCMAKE_BUILD_TYPE="Release" -DENABLE_TESTING=YES -DUSE_OPENMP=YES
    - make -j
    - python3 generate_ic.py
    - ./bin/cato.x input.ini
    - mv results/* .
    - python3 view_results.py
  artifacts:
    paths:
      - /builds/smil/cato/tests/integrated/kelvin_helmholtz/kh_2d_results.png

sedov_2d:
  stage: test
  script:
    - cd tests/integrated/sedov/
    - cmake ../../.. -DCMAKE_BUILD_TYPE="Release" -DENABLE_TESTING=YES -DUSE_OPENMP=YES
    - make -j
    - python3 generate_ic.py
    - ./bin/cato.x input.ini
    - mv results/* .
    - python3 view_results.py
  artifacts:
    paths:
      - /builds/smil/cato/tests/integrated/sedov/sedov_2d_results.png

  #   - mv results/* .
  #   - python3 view_results.py
  # artifacts:
  #   paths:
  #     - sod_1d_results.png

# Example artifacts
#   stage: test
#   script:
#     - mkdir -p iceblock_release_intel_17U4
#     - chown -R newuser iceblock_release_intel_17U4 # need a diff user to run mpirun
#     - chmod -R u+rX iceblock_release_intel_17U4
#     - cd iceblock_release_intel_17U4
#     - source /opt/intel/17U4/bin/compilervars.sh intel64
#     - cmake .. -DCMAKE_Fortran_COMPILER=mpiifort -DCMAKE_BUILD_TYPE=Debug -DCGNS_INCLUDE_DIR=/opt/cgns/include -DCGNS_LIBRARY=/opt/cgns/lib
#     - make -j
#     - cp ../tests/integrated_tests/uniform_iceblock_test/input.nml .
#     - ./iris3d input.nml
#     - cp ../tests/regression_tests/uniform_iceblock_test/report.ipynb iceblock_report.ipynb
#     - ls
#     - jupyter nbconvert --ExecutePreprocessor.timeout=600 --execute --allow-errors --to html iceblock_report.html iceblock_report.ipynb
#     - ls
#     - echo $CI_PROJECT_DIR
#     - echo $PWD
#   artifacts:
#       paths:
#       - iceblock_release_intel_17U4/dsum.csv
#       - iceblock_release_intel_17U4/dnde_spectra.png
#       - iceblock_release_intel_17U4/iceblock_report.ipynb
#       - iceblock_release_intel_17U4/iceblock_report.html
#       - iceblock_release_intel_17U4/dt_fit_sum.csv
#       - iceblock_release_intel_17U4/dd_fit_sum.csv
