image: docker.io/smillerc/gfortran-dev:latest

# Set the thread count for OpenMP runs
variables:
  OMP_NUM_THREADS: 2
  HDF5_DISABLE_VERSION_CHECK: 2

before_script:
  - /bin/bash
  - eval `spack load --sh hdf5`
  - pip install fypp "dask[complete]" --user

stages:
  - build
  - test

debug:
  stage: build
  script:
    - mkdir -p debug
    - cd debug
    - cmake .. -DCMAKE_BUILD_TYPE="Debug" -DENABLE_COARRAY=ON -DENABLE_TESTING=ON -DUSE_OPENMP_SIMD=ON
    - make -j
    - ctest --output-on-failure

release:
  stage: build
  script:
    - mkdir -p release
    - cd release
    - pwd
    - cmake .. -DCMAKE_BUILD_TYPE="Release" -DENABLE_COARRAY=ON -DENABLE_TESTING=OFF -DUSE_OPENMP_SIMD=ON
    - make -j
    - ctest --output-on-failure

integration_tests:
  stage: test
  script:
    - mkdir -p build
    - cd build
    - cmake .. -DCMAKE_BUILD_TYPE="Release" -DENABLE_COARRAY=ON -DENABLE_TESTING=OFF -DUSE_OPENMP_SIMD=ON
    - make -j
    - cd ../tests/integrated
    - ./run_integration_tests.sh gnu
    - ls test_results
  artifacts:
    paths:
      - /builds/smil/cato/tests/integrated/test_results

single_debug_run:
  stage: test
  script:
    - cd tests/integrated/sedov/
    - cmake ../../.. -DCMAKE_BUILD_TYPE="Debug" -DENABLE_COARRAY=ON -DENABLE_TESTING=ON -DUSE_OPENMP_SIMD=ON
    - make -j
    - python3 generate_ic.py
    - ./bin/cato.x input.ini
    - python3 view_results.py
    - cp sedov_2d_results.png sedov_2d_debug_results.png
  artifacts:
    paths:
      - /builds/smil/cato/tests/integrated/sedov/sedov_2d_debug_results.png
