repos:
-   repo: https://github.com/ambv/black
    rev: stable
    hooks:
    - id: black

-   repo: https://github.com/pseewald/fprettify
    rev: v0.3.6
    hooks:
    - id: fprettify
      args: ['--indent', '2', '--whitespace', '3', '--whitespace-intrinsics', 'False', '--strict-indent', '--enable-replacements', '--c-relations']

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v1.2.3
    hooks:
    - id: end-of-file-fixer
    - id: fix-encoding-pragma
    - id: trailing-whitespace
